services:
  - type: web
    name: currents-demo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
